version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
      CLERK_SECRET_KEY: $CLERK_SECRET_KEY
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: $NEXT_PUBLIC_CLERK_SIGN_IN_URL
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: $NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
      NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: $NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
      DATABASE_URL: mysql://root:$MYSQL_ROOT_PASSWORD@db:3306/discord-clone
      UPLOADTHING_TOKEN: $UPLOADTHING_TOKEN
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: discord-clone
    volumes:
      - discord:/var/lib/mysql

volumes:
  discord:
